import Badge, { type BadgeTone } from "@/components/Badge";
import ResultSection from "@/components/ResultSection";
import type { AppealSource, AppealStatus, GeneratedAppeal } from "@/lib/types";
import { parseConfidenceScore } from "@/lib/types";

export interface PacketSummary {
  insurance: string;
  procedureCode: string;
  deniedAmount: string;
  source: AppealSource;
  status?: AppealStatus;
}

export const statusTone: Record<AppealStatus, BadgeTone> = {
  Draft: "slate",
  Generated: "blue",
  Ready: "green",
  "Needs Review": "amber",
  Submitted: "indigo",
  Paid: "green",
  "Denied Again": "red",
};

function confidenceMeter(score: number): { label: string; bar: string; text: string } {
  if (score >= 75)
    return { label: "Strong", bar: "bg-emerald-500", text: "text-emerald-700" };
  if (score >= 55)
    return { label: "Moderate", bar: "bg-blue-600", text: "text-blue-700" };
  return { label: "Needs work", bar: "bg-amber-500", text: "text-amber-700" };
}

const checklistText = (items: string[]) =>
  items.map((i) => `• ${i}`).join("\n");

const usd = (raw: string) => {
  const n = parseFloat(raw);
  if (!raw || Number.isNaN(n)) return "—";
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
};

const sectionIcons = {
  letter: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M4 5h16v14H4z" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M4 7l8 5 8-5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  docs: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M9 11l3 3 8-8M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  narrative: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M4 6h16M4 12h16M4 18h10" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  steps: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M9 5h11M9 12h11M9 19h11M4 5h.01M4 12h.01M4 19h.01" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  phone: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2 4.2 2 2 0 0 1 4 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a2 2 0 0 1-.5 2.1L8 9.6a16 16 0 0 0 6 6l1.2-1.1a2 2 0 0 1 2.1-.5c.8.3 1.7.5 2.6.6a2 2 0 0 1 1.7 2Z" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  note: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M14 3v4a1 1 0 0 0 1 1h4M5 3h9l5 5v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
};

export default function AppealPacket({
  result,
  summary,
}: {
  result: GeneratedAppeal;
  summary: PacketSummary;
}) {
  const confidence = parseConfidenceScore(result.confidenceScore);
  const meter = confidenceMeter(confidence);

  return (
    <div className="mt-8 flex flex-col gap-6">
      {/* Summary card */}
      <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-6 py-4">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-slate-500">
            Packet summary
          </h2>
          <div className="flex items-center gap-2">
            {summary.source === "claude" ? (
              <Badge tone="blue" dot>
                Generated by Claude
              </Badge>
            ) : (
              <Badge tone="slate" dot>
                Demo mode
              </Badge>
            )}
            {summary.status && (
              <Badge tone={statusTone[summary.status]} dot>
                {summary.status}
              </Badge>
            )}
          </div>
        </div>
        <div className="grid gap-6 p-6 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-slate-400">
              Insurance
            </dt>
            <dd className="mt-1.5 text-sm font-semibold text-slate-900">
              {summary.insurance || "—"}
            </dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-slate-400">
              Procedure
            </dt>
            <dd className="mt-1.5">
              <span className="rounded-md bg-slate-100 px-2 py-0.5 font-mono text-sm text-slate-800">
                {summary.procedureCode || "—"}
              </span>
            </dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-slate-400">
              Denied amount
            </dt>
            <dd className="mt-1.5 text-sm font-semibold tabular-nums text-slate-900">
              {usd(summary.deniedAmount)}
            </dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-slate-400">
              Confidence
            </dt>
            <dd className="mt-1.5">
              <div className="flex items-baseline gap-2">
                <span className="text-lg font-semibold tabular-nums text-slate-900">
                  {result.confidenceScore}
                </span>
                <span className={`text-xs font-medium ${meter.text}`}>
                  {meter.label}
                </span>
              </div>
              <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-slate-100">
                <div
                  className={`h-full rounded-full ${meter.bar}`}
                  style={{ width: `${Math.max(4, Math.min(100, confidence))}%` }}
                />
              </div>
            </dd>
          </div>
        </div>
        {/* Revenue-focused callout */}
        <div className="flex items-start gap-3 border-t border-slate-100 bg-slate-50/60 px-6 py-4">
          <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-slate-900 text-white">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </span>
          <p className="text-sm text-slate-600">
            Review and submit this packet to pursue recovery of{" "}
            <span className="font-semibold text-slate-900">
              {usd(summary.deniedAmount)}
            </span>{" "}
            in denied revenue.
          </p>
        </div>
      </div>

      {/* Human review required */}
      <div className="flex items-start gap-3 rounded-2xl border border-amber-200/70 bg-amber-50/60 px-5 py-4">
        <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700">
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M12 9v4M12 17h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
        <div>
          <p className="text-sm font-semibold text-slate-900">
            Human review required
          </p>
          <p className="mt-0.5 text-sm leading-relaxed text-slate-600">
            AI-generated content is for billing support only. A qualified billing
            professional must review all materials before submission.
          </p>
        </div>
      </div>

      {/* Sections */}
      <div className="flex flex-col gap-5">
        <ResultSection
          title="Appeal Letter"
          description="Ready to place on practice letterhead."
          copyText={result.appealLetter}
          icon={sectionIcons.letter}
        >
          <pre className="whitespace-pre-wrap font-sans">
            {result.appealLetter}
          </pre>
        </ResultSection>

        <ResultSection
          title="Missing Document Checklist"
          description="Attach these before resubmitting."
          copyText={checklistText(result.missingDocuments)}
          icon={sectionIcons.docs}
        >
          <ul className="flex flex-col gap-2.5">
            {result.missingDocuments.map((d, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <span className="mt-0.5 text-slate-400">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="4" y="4" width="16" height="16" rx="5" />
                  </svg>
                </span>
                {d}
              </li>
            ))}
          </ul>
        </ResultSection>

        <ResultSection
          title="Clinical Narrative"
          description="Supports medical/dental necessity."
          copyText={result.clinicalNarrative}
          icon={sectionIcons.narrative}
        >
          <pre className="whitespace-pre-wrap font-sans">
            {result.clinicalNarrative}
          </pre>
        </ResultSection>

        <ResultSection
          title="Resubmission Checklist"
          description="Steps to complete before sending."
          copyText={checklistText(result.resubmissionChecklist)}
          icon={sectionIcons.steps}
        >
          <ol className="flex flex-col gap-2.5">
            {result.resubmissionChecklist.map((s, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xs font-semibold text-blue-700">
                  {i + 1}
                </span>
                {s}
              </li>
            ))}
          </ol>
        </ResultSection>

        <ResultSection
          title="Payer Call Script"
          description="Use when calling the insurer."
          copyText={result.payerCallScript}
          icon={sectionIcons.phone}
        >
          <pre className="whitespace-pre-wrap font-sans">
            {result.payerCallScript}
          </pre>
        </ResultSection>

        <ResultSection
          title="Internal Billing Note"
          description="For your team — not sent to the payer."
          copyText={result.internalBillingNote}
          icon={sectionIcons.note}
        >
          <pre className="whitespace-pre-wrap font-sans">
            {result.internalBillingNote}
          </pre>
        </ResultSection>
      </div>

      {/* Risk warnings — subtle amber, clear but calm */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <p className="flex items-center gap-2 text-sm font-semibold text-slate-800">
          <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-amber-50 text-amber-600 ring-1 ring-inset ring-amber-100">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 9v4M12 17h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </span>
          Risk warnings
        </p>
        <ul className="mt-4 grid gap-2.5 sm:grid-cols-2">
          {result.riskWarnings.map((w, i) => (
            <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-400" />
              {w}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
